/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package isw1;



import java.sql.Time;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;



/**
 *
 * @author Rodriguez
 */
public class Principal extends javax.swing.JFrame {
    private CarritoDeCompras cdc;
    private DefaultListModel dm = new DefaultListModel();
    private double precioFinal=0;
    Date now = new Date();
    private boolean mapa=false;

    /**
     * Creates new form Principal
     */
    public Principal( CarritoDeCompras c) {
        cdc=c;
        
        initComponents();
        this.setSize(1050, 650);
        
        cmbPago.addItem("Efectivo");
        cmbPago.addItem("Tarjeta");
        cmbPago.setSelectedIndex(-1);
        
        cmbEntrega.addItem("Lo mas rapido");
        cmbEntrega.addItem("Programar Entrega");
        cmbEntrega.setSelectedIndex(0);
        
        cmbEnvio.addItem("Direccion");
        cmbEnvio.addItem("Mapa");
        cmbEnvio.setSelectedIndex(0);
        
        for (int i = 0; i < 25; i++) {//Lleno el vector de hora
           cmbHora.addItem(String.valueOf(i));
            }
        for (int i = 0; i < 61; i++) {
            cmbMinutos.addItem(String.valueOf(i));
        }
        
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        
        Producto productos[] = cdc.getProductos();
        for (int i = 0; i <productos.length; i++) {
          dm.addElement(new ImgsNText(productos[i].getNombre()+" $" + productos[i].getPrecio(), productos[i].getImg(),productos[i].getPrecio()));
          precioFinal+= productos[i].getPrecio();
        }
        total.setText("Total:$" + String.valueOf(precioFinal));
        lblNombreComercio.setText(cdc.getComercio().getNombre());
        lista.setCellRenderer(new Renderer());
        lista.setModel(dm);
        jLayeredPane2.setVisible(false);
        panelEntrega.setVisible(false);
        
       
         
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombreComercio = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        total = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEfectivo = new javax.swing.JTextField();
        lblVuelto = new javax.swing.JLabel();
        vuelto = new javax.swing.JLabel();
        paneTarjeta = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtNombreTarjeta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNumeroTarjeta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCodigoTarjeta = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtFechaTarjeta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbPago = new javax.swing.JComboBox<>();
        panelEntrega = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        calendario = new com.toedter.calendar.JCalendar();
        jLabel8 = new javax.swing.JLabel();
        cmbHora = new javax.swing.JComboBox<>();
        cmbMinutos = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmbEntrega = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cmbEnvio = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        paneEnvioDireccion = new javax.swing.JLayeredPane();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtBarrio = new javax.swing.JTextField();
        txtCalle = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtPiso = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtDepto = new javax.swing.JTextField();
        paneEnvioMapa = new javax.swing.JLayeredPane();
        jLabel18 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMaximumSize(new java.awt.Dimension(538, 90));
        jPanel1.setMinimumSize(new java.awt.Dimension(538, 90));

        jScrollPane2.setViewportView(lista);

        total.setText("Total:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNombreComercio, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombreComercio, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(total))
        );

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("¿Con cuánto va a pagar?");

        jLabel3.setText("Su vuelto será de:");

        txtEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEfectivoActionPerformed(evt);
            }
        });
        txtEfectivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEfectivoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEfectivoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEfectivoKeyTyped(evt);
            }
        });

        vuelto.setText("         ");

        jLayeredPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtEfectivo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblVuelto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(vuelto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vuelto, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVuelto))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblVuelto)
                    .addComponent(vuelto))
                .addContainerGap())
        );

        paneTarjeta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Tarjetas:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Visa" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Nombre y apellido:");

        txtNombreTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreTarjetaActionPerformed(evt);
            }
        });
        txtNombreTarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreTarjetaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreTarjetaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreTarjetaKeyTyped(evt);
            }
        });

        jLabel7.setText("Numero de tarjeta:");

        txtNumeroTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroTarjetaActionPerformed(evt);
            }
        });
        txtNumeroTarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumeroTarjetaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumeroTarjetaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroTarjetaKeyTyped(evt);
            }
        });

        jLabel10.setText("Codigo de seguridad:");

        txtCodigoTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoTarjetaActionPerformed(evt);
            }
        });
        txtCodigoTarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoTarjetaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoTarjetaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoTarjetaKeyTyped(evt);
            }
        });

        jLabel11.setText("Fecha de Vencimiento:");

        txtFechaTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaTarjetaActionPerformed(evt);
            }
        });
        txtFechaTarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFechaTarjetaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFechaTarjetaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaTarjetaKeyTyped(evt);
            }
        });

        paneTarjeta.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneTarjeta.setLayer(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneTarjeta.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneTarjeta.setLayer(txtNombreTarjeta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneTarjeta.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneTarjeta.setLayer(txtNumeroTarjeta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneTarjeta.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneTarjeta.setLayer(txtCodigoTarjeta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneTarjeta.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneTarjeta.setLayer(txtFechaTarjeta, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout paneTarjetaLayout = new javax.swing.GroupLayout(paneTarjeta);
        paneTarjeta.setLayout(paneTarjetaLayout);
        paneTarjetaLayout.setHorizontalGroup(
            paneTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTarjetaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(paneTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneTarjetaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreTarjeta))
                    .addGroup(paneTarjetaLayout.createSequentialGroup()
                        .addGroup(paneTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneTarjetaLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneTarjetaLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneTarjetaLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 103, Short.MAX_VALUE))
                    .addGroup(paneTarjetaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumeroTarjeta)))
                .addContainerGap())
        );
        paneTarjetaLayout.setVerticalGroup(
            paneTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTarjetaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNombreTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCodigoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtFechaTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Registrar Pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Forma de Pago:");

        cmbPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        cmbPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPagoActionPerformed(evt);
            }
        });

        jLabel4.setText("Fecha de entrega:");

        calendario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calendarioMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                calendarioMouseReleased(evt);
            }
        });
        calendario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                calendarioKeyReleased(evt);
            }
        });

        jLabel8.setText("Horario de entrega:");

        cmbHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        cmbMinutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        jLabel9.setText(":");

        panelEntrega.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelEntrega.setLayer(calendario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelEntrega.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelEntrega.setLayer(cmbHora, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelEntrega.setLayer(cmbMinutos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelEntrega.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelEntregaLayout = new javax.swing.GroupLayout(panelEntrega);
        panelEntrega.setLayout(panelEntregaLayout);
        panelEntregaLayout.setHorizontalGroup(
            panelEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEntregaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEntregaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEntregaLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEntregaLayout.setVerticalGroup(
            panelEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEntregaLayout.createSequentialGroup()
                .addGroup(panelEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jLabel12.setText("Forma de Entrega:");

        cmbEntrega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        cmbEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEntregaActionPerformed(evt);
            }
        });

        jLabel13.setText("Envio:");

        cmbEnvio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        cmbEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEnvioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(cmbEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cmbEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cmbEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(panelEntrega)
                .addGap(25, 25, 25))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        paneEnvioDireccion.setMaximumSize(new java.awt.Dimension(538, 90));

        jLabel14.setText("Calle:");

        jLabel15.setText("Numero:");

        jLabel16.setText("Piso:");

        jLabel17.setText("Barrio:");

        jLabel19.setText("Depto.:");

        paneEnvioDireccion.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneEnvioDireccion.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneEnvioDireccion.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneEnvioDireccion.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneEnvioDireccion.setLayer(txtBarrio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneEnvioDireccion.setLayer(txtCalle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneEnvioDireccion.setLayer(txtNumero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneEnvioDireccion.setLayer(txtPiso, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneEnvioDireccion.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneEnvioDireccion.setLayer(txtDepto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout paneEnvioDireccionLayout = new javax.swing.GroupLayout(paneEnvioDireccion);
        paneEnvioDireccion.setLayout(paneEnvioDireccionLayout);
        paneEnvioDireccionLayout.setHorizontalGroup(
            paneEnvioDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneEnvioDireccionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneEnvioDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneEnvioDireccionLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneEnvioDireccionLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDepto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneEnvioDireccionLayout.setVerticalGroup(
            paneEnvioDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneEnvioDireccionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneEnvioDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17)
                    .addComponent(txtBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneEnvioDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtDepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        paneEnvioMapa.setMaximumSize(new java.awt.Dimension(538, 90));
        paneEnvioMapa.setPreferredSize(new java.awt.Dimension(538, 90));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/isw1/map.jpg"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        paneEnvioMapa.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout paneEnvioMapaLayout = new javax.swing.GroupLayout(paneEnvioMapa);
        paneEnvioMapa.setLayout(paneEnvioMapaLayout);
        paneEnvioMapaLayout.setHorizontalGroup(
            paneEnvioMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneEnvioMapaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneEnvioMapaLayout.setVerticalGroup(
            paneEnvioMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneEnvioMapaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(paneEnvioMapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(paneEnvioDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneEnvioDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneEnvioMapa, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton2.setText("Ver Pedidos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(paneTarjeta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTotal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paneTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPagoActionPerformed
        // TODO add your handling code here:
        if(cmbPago.getSelectedIndex()==0)
        {
            jLayeredPane2.setVisible(true);//Muestra el panel de efectivo
            paneTarjeta.setVisible(false);
            
            
        }
        if(cmbPago.getSelectedIndex()==1)
        {
           
            jLayeredPane2.setVisible(false);
            paneTarjeta.setVisible(true);
            
        }
        
        
    }//GEN-LAST:event_cmbPagoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(comprobar()==true)
        {
            Persistencia P = new Persistencia();
            JOptionPane.showMessageDialog(null,  "Registro Satisfactorio", "Exito", 3);
            Pedido pedido=this.crearPedido();
            P.grabar(pedido);
            this.limpiarCampos();
        }
        else
        {
           
            JOptionPane.showMessageDialog(null,  "Campos incorrectos o incompletos", "Error", 2);
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtEfectivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEfectivoKeyTyped
        char C = evt.getKeyChar();
        
        if(Character.isLetter(C))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this,"Ingrese solo numeros");
            txtEfectivo.setCursor(null);
            
            
        }
        else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
                || (int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
                || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
                || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255) 
        {
            
                getToolkit().beep();
                evt.consume();
                JOptionPane.showMessageDialog(this,"Ingrese solo numeros");
                

            
        }
       
    }//GEN-LAST:event_txtEfectivoKeyTyped

    private void txtEfectivoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEfectivoKeyReleased
        // TODO add your handling code here:
         try
        {
            if("".equals(txtEfectivo.getText()))
            {
                vuelto.setText("");
            }
            else
            {
                vuelto.setText(String.valueOf(Double.parseDouble(txtEfectivo.getText())-precioFinal));
            }
                
        }
        catch( Exception e)
        {

        }
        
    }//GEN-LAST:event_txtEfectivoKeyReleased

    private void txtEfectivoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEfectivoKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtEfectivoKeyPressed

    private void txtEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEfectivoActionPerformed

    }//GEN-LAST:event_txtEfectivoActionPerformed

    private void calendarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_calendarioKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_calendarioKeyReleased

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void calendarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarioMouseClicked
              // TODO add your handling code here:
    }//GEN-LAST:event_calendarioMouseClicked

    private void calendarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarioMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarioMouseReleased

    private void txtNombreTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreTarjetaActionPerformed

    private void txtNombreTarjetaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreTarjetaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreTarjetaKeyPressed

    private void txtNombreTarjetaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreTarjetaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreTarjetaKeyReleased

    private void txtNombreTarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreTarjetaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreTarjetaKeyTyped

    private void txtNumeroTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroTarjetaActionPerformed

    private void txtNumeroTarjetaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroTarjetaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroTarjetaKeyPressed

    private void txtNumeroTarjetaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroTarjetaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroTarjetaKeyReleased

    private void txtNumeroTarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroTarjetaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroTarjetaKeyTyped

    private void txtCodigoTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoTarjetaActionPerformed

    private void txtCodigoTarjetaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoTarjetaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoTarjetaKeyPressed

    private void txtCodigoTarjetaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoTarjetaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoTarjetaKeyReleased

    private void txtCodigoTarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoTarjetaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoTarjetaKeyTyped

    private void txtFechaTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaTarjetaActionPerformed

    private void txtFechaTarjetaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaTarjetaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaTarjetaKeyPressed

    private void txtFechaTarjetaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaTarjetaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaTarjetaKeyReleased

    private void txtFechaTarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaTarjetaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaTarjetaKeyTyped

    private void cmbEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEntregaActionPerformed
        // TODO add your handling code here:
        if(cmbEntrega.getSelectedIndex()==0)
        {
            this.panelEntrega.setVisible(false);
            
            
        }
        if(cmbEntrega.getSelectedIndex()==1)
        {
           this.panelEntrega.setVisible(true);
            
            
        }
       
    }//GEN-LAST:event_cmbEntregaActionPerformed

    private void cmbEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEnvioActionPerformed
        // TODO add your handling code here:
        if(cmbEnvio.getSelectedIndex()==0)
        {
            paneEnvioDireccion.setVisible(true);
            paneEnvioMapa.setVisible(false);    
        }
        if(cmbEnvio.getSelectedIndex()==1)
        {
           
            paneEnvioDireccion.setVisible(false);
            paneEnvioMapa.setVisible(true); 
        }
        
    }//GEN-LAST:event_cmbEnvioActionPerformed

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
            mapa=true;
        
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Main m = new Main();
        m.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private boolean comprobar()
    {
//        try
//        {
//            DateFormat hur = new SimpleDateFormat("HH:mm:ss");
//            String horario = (String)cmbHora.getSelectedItem()+":"+(String)cmbMinutos.getSelectedItem()+":"+"00";
//            System.out.println("horario"+horario);
//                    Date conver = hur.parse(horario);
//                    System.out.println(conver.toString());
//        }catch(Exception e){}
        
        
        if(this.cmbPago.getSelectedIndex()==-1)//Si no selecciona ningun medio de pago, retorna false
        {
            return false;
        }
        else
        {
            if(this.cmbPago.getSelectedIndex()==0)//Verifica si el medio de pago es Efectivo
            {
                switch(txtEfectivo.getText())//Devuelve falso si el monto a pagar en efectivo esta vacio o tiene hasta 5 espacion
                {
                    case "":case " ":case "  ":case "   ":case "    ":
                        return false;
                }
                try//Intenta validar si el efectivo ingresado es mayor que el costo final
                {
                    if(Double.parseDouble(txtEfectivo.getText())<precioFinal)//Valida si el efectivo ingresado es mayor que el costo final
                    {
                        return false;
                    }
                }
                catch(Exception e)
                {
                    return false;
                }
                
            }
            else
            {
                if(("").equals(txtNombreTarjeta.getText()) ||("").equals(txtNumeroTarjeta.getText()) || ("").equals(txtCodigoTarjeta.getText()) ||("").equals(txtFechaTarjeta.getText())) // Valida que ningun campo de la tarjeta este vacio
                {
                    return false;
                }
                
                
            }
            
            if(this.cmbPago.getSelectedIndex()==1)//Verifica si el medio de pago es Tajeta
            {
                
                if(this.jComboBox1.getSelectedIndex()==-1)
                {
                    return false;
                }
            }
        }
        

            
            
            if(this.cmbEnvio.getSelectedIndex()==0)//Si la entrega es con dirección
            {
                if(("").equals(txtBarrio.getText()) || ("").equals(txtCalle.getText()) || ("").equals(txtNumero.getText()))//Verifica si algun campo de direccion esta vacio
                {
                    return false;
                }
            }
            else
            {
                if(mapa==false)
                {
                    return false;
                }
            }
            
            if(cmbEntrega.getSelectedIndex()==1)//Verifica si se eligió programar la entrega
            {
                if((this.calendario.getDate()).compareTo(now) < 0 ) //Verifica que el dia elegido sea mayor que hoy
                {
                    return false;
                }
                try
                {
                    DateFormat hour = new SimpleDateFormat("HH:mm:ss");
                    Date convertido = hour.parse((String)cmbHora.getSelectedItem()+":"+(String)cmbMinutos.getSelectedItem()+":00");
                    System.out.println(convertido.toString());
                    
                    if(this.calendario.getDate().getDay()==now.getDay() && calendario.getDate().getMonth() == now.getMonth() && calendario.getDate().getYear()==now.getYear())//Verifica que la fecha elegida sea la de hoy
                    {
                    Time horaPedido=Time.valueOf(convertido.getHours()+":"+convertido.getMinutes()+":"+convertido.getSeconds());
                    Time horaActual= Time.valueOf(now.getHours()+":"+now.getMinutes()+":"+now.getSeconds());
                        
                        if(horaPedido.compareTo(horaActual)<1)//Valida que si la hora a programar es menor a la actual, rechace la validacion
                        {
                            return false;
                        }
                    }
                    
                    
                }
                catch(Exception e)
                {
                    return false;
                }
            }
        
        
        return true;
    }
    private void limpiarCampos()
    {
        cmbEnvio.setSelectedIndex(-1);
        cmbPago.setSelectedIndex(-1);
        cmbEntrega.setSelectedIndex(-1);
        paneEnvioDireccion.setVisible(false);
        paneEnvioMapa.setVisible(false);  
        jLayeredPane2.setVisible(false);
        paneTarjeta.setVisible(false);
        this.panelEntrega.setVisible(false);

        txtEfectivo.setText("");
        txtNombreTarjeta.setText("");
        txtFechaTarjeta.setText("");
        txtNumeroTarjeta.setText("");
        txtCodigoTarjeta.setText("");
        txtBarrio.setText("");
        txtDepto.setText("");
        txtPiso.setText("");
        txtCalle.setText("");
        txtNumero.setText("");
        vuelto.setText("");
        mapa=false;
    }
    
    private Pedido crearPedido()
    {
        Pedido P;
        Persistencia per = new Persistencia();
        if(cmbEnvio.getSelectedIndex()==0)//Si el usuario elije la direccion por medio de llenado de campos
        {
            //Creo el objeto con datos de direccion
            P=new Pedido(txtBarrio.getText(),txtCalle.getText(),txtNumero.getText(),txtPiso.getText(),txtDepto.getText(),String.valueOf(precioFinal));
        }
        else
        {
            P=new Pedido(String.valueOf(precioFinal));
            
        }
        if(cmbPago.getSelectedIndex()==1) //Si el usuario elije pagar con tarjeta
            {
                P.setCodigoTarjeta(txtCodigoTarjeta.getText());
                P.setNumeroTarjeta(txtNumeroTarjeta.getText());
                P.setFechaVencimientoTarjeta(txtFechaTarjeta.getText());
                P.setNombreApellidoTarjeta(txtNombreTarjeta.getText());
                P.setFormaPago("Tarjeta");
            }
        else
        {
            P.setFormaPago("Efectivo");
        }
        if(cmbEntrega.getSelectedIndex()==1)//Si elije programar la fecha
            {
              P.setFechaEntrega(calendario.getDate());
              try
                {
                    DateFormat hour = new SimpleDateFormat("HH:mm:ss");
                    //Date convertido = hour.parse(txtHora.getText());
                   // Time horaPedido=Time.valueOf(convertido.getHours()+":"+convertido.getMinutes()+":"+convertido.getSeconds());
                    //P.setHoraEntrega(horaPedido);
                    P.setFormaEntrega("Programada");
                    
                }
                catch(Exception e)
                {
                    System.out.println(e.toString());
                }
            }
        else
        {
            P.setFormaEntrega("Lo antes posible");
            P.setFechaEntrega(now);
        }
        
        P.setNumeroPedido(per.getNumeroPedido());
        
        return P;
            
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar calendario;
    private javax.swing.JComboBox<String> cmbEntrega;
    private javax.swing.JComboBox<String> cmbEnvio;
    private javax.swing.JComboBox<String> cmbHora;
    private javax.swing.JComboBox<String> cmbMinutos;
    private javax.swing.JComboBox<String> cmbPago;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNombreComercio;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblVuelto;
    private javax.swing.JList<String> lista;
    private javax.swing.JLayeredPane paneEnvioDireccion;
    private javax.swing.JLayeredPane paneEnvioMapa;
    private javax.swing.JLayeredPane paneTarjeta;
    private javax.swing.JLayeredPane panelEntrega;
    private javax.swing.JLabel total;
    private javax.swing.JTextField txtBarrio;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtCodigoTarjeta;
    private javax.swing.JTextField txtDepto;
    private javax.swing.JTextField txtEfectivo;
    private javax.swing.JTextField txtFechaTarjeta;
    private javax.swing.JTextField txtNombreTarjeta;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtNumeroTarjeta;
    private javax.swing.JTextField txtPiso;
    private javax.swing.JLabel vuelto;
    // End of variables declaration//GEN-END:variables
}
